name: Build and test Go
on: [push]
env:
  # Test projects in KBC for E2E tests
  TEST_KBC_PROJECTS: |
    connection.keboola.com|9293|${{ secrets.TEST_KBC_PROJECT_9293_TOKEN }};
    connection.keboola.com|9294|${{ secrets.TEST_KBC_PROJECT_9294_TOKEN }};
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency:
      group: e2e-tests
      cancel-in-progress: false
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          make install-tools

      - name: Lint and test
        run: |
          make lint
          make tests
