name: Build and test Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency:
      group: e2e-tests
      cancel-in-progress: false
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version: ${{ env.GO_VERSION }}

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set TEST_KBC_PROJECTS_FILE entries
        uses: ./.github/export-kbc-projects
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Install tools
        run: |
          make install-tools

      - name: Lint and test
        run: |
          make lint
          make tests
        env:
          TEST_KBC_PROJECTS_LOCK_HOST: ${{ vars.TEST_KBC_PROJECTS_LOCK_HOST }}
          TEST_KBC_PROJECTS_LOCK_PASSWORD: ${{ secrets.TEST_KBC_PROJECTS_LOCK_PASSWORD }}
          TEST_KBC_PROJECTS_FILE: '${{ github.workspace }}/${{ vars.TEST_KBC_PROJECTS_FILE }}'

