name: Build and test Go
on: [push]
env:
  # Test projects in KBC for E2E tests
  TEST_KBC_PROJECTS: '[{"host":"connection.keboola.com","project":9293,"token":"${{ secrets.TEST_KBC_PROJECT_9293_TOKEN }}","stagingStorage":"s3","backend":"snowflake"},{"host":"connection.keboola.com","project":9294,"token":"${{ secrets.TEST_KBC_PROJECT_9294_TOKEN }}","stagingStorage":"s3","backend":"snowflake"},{"host":"connection.north-europe.azure.keboola.com","project":10669,"token":"${{ secrets.TEST_KBC_PROJECT_NE_10669_TOKEN }}","stagingStorage":"abs","backend":"snowflake"},{"host":"connection.keboola.com","project":9851,"token":"${{ secrets.TEST_KBC_PROJECT_9851_TOKEN }}","stagingStorage":"gcs","backend":"bigquery"},{"host":"connection.keboola.com","project":9493,"token":"${{ secrets.TEST_KBC_PROJECT_QUEUEV1_9493_TOKEN }}","stagingStorage":"s3","backend":"snowflake","queue":"v1"}]'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency:
      group: e2e-tests
      cancel-in-progress: false
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          make install-tools

      - name: Lint and test
        run: |
          make lint
          make tests

